export const techStackList: Technologies[] = [
  {
    name: "HTML",
    icon: "simple-icons:html5",
    size: 32,
    color: "text-icon-html",
  },
  {
    name: "CSS",
    icon: "simple-icons:css3",
    size: 32,
    color: "text-icon-css",
  },
  {
    name: "JavaScript",
    icon: "simple-icons:javascript",
    size: 32,
    color: "text-icon-js",
  },
  {
    name: "TypeScript",
    icon: "simple-icons:typescript",
    size: 36,
    color: "text-icon-ts",
  },
  {
    name: "React",
    icon: "simple-icons:react",
    size: 32,
    color: "text-icon-react",
  },
  {
    name: "Expo",
    icon: "simple-icons:expo",
    size: 32,
    color: "text-fg-500",
  },
  {
    name: "Tailwind",
    icon: "simple-icons:tailwindcss",
    size: 32,
    color: "text-icon-tailwind",
  },
  {
    name: "ThreeJS",
    icon: "simple-icons:threedotjs",
    size: 32,
    color: "text-fg-500",
  },
  {
    name: "NodeJS",
    icon: "simple-icons:nodedotjs",
    size: 32,
    color: "text-icon-node",
  },
  {
    name: "Bun",
    icon: "simple-icons:bun",
    size: 32,
    color: "text-icon-bun",
  },
  {
    name: "Golang",
    icon: "simple-icons:go",
    size: 32,
    color: "text-icon-go",
  },
  {
    name: "FastAPI",
    icon: "simple-icons:fastapi",
    size: 32,
    color: "text-icon-fastapi",
  },
  {
    name: "Godot",
    icon: "simple-icons:godotengine",
    size: 32,
    color: "text-icon-godot",
  },
  {
    name: "Lua",
    icon: "simple-icons:lua",
    size: 32,
    color: "text-icon-lua",
  },
  {
    name: "Linux",
    icon: "simple-icons:linux",
    size: 32,
    color: "text-icon-linux",
  },
  {
    name: "Neon",
    icon: "simple-icons:neon",
    size: 32,
    color: "text-icon-neon",
  },
  {
    name: "Supabase",
    icon: "simple-icons:supabase",
    size: 32,
    color: "text-icon-supabase",
  },
  {
    name: "SQLite",
    icon: "simple-icons:sqlite",
    size: 32,
    color: "text-fg-500",
  },
  {
    name: "GitHub",
    icon: "simple-icons:github",
    size: 32,
    color: "text-fg-500",
  },
  {
    name: "BetterAuth",
    icon: "simple-icons:betterauth",
    size: 32,
    color: "text-fg-500",
  },
  {
    name: "Rust",
    icon: "simple-icons:rust",
    size: 32,
    color: "text-fg-500",
  },
  {
    name: "Claude Code",
    icon: "simple-icons:claude",
    size: 32,
    color: "text-icon-claude",
  },
  {
    name: "Cloudflare",
    icon: "simple-icons:cloudflare",
    size: 32,
    color: "text-icon-cloudflare",
  },
  {
    name: "Fedora",
    icon: "simple-icons:fedora",
    size: 32,
    color: "text-icon-fedora",
  },
  {
    name: "Ghostty",
    icon: "simple-icons:ghostty",
    size: 32,
    color: "text-icon-ghostty",
  },
];
